config/routes.rb
Assignment5::Application.routes.draw do

  resources :items

  resources :customers do
        resources :orders
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :contact, :name, :phone
  has_many :orders
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name
  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :item_id, :quantity, :total_cost #, :item_name
  belongs_to :customer
  belongs_to :item
  validates :customer_id, :presence=> { :message=>"Customer name must be provided" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :convert_customer_name_to_id, :only => [:create, :update]
  # GET /orders
  # GET /orders.json
  def index
    @orders = Customer.find_by_id(params[:customer_id]).orders #Orders.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Customer.find_by_id(params[:customer_id]).orders.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
  private
  def convert_customer_name_to_id
    customer_name = params[:order][:customer_name]
    customer = Customer.find_by_name(customer_name)
    params[:order].delete(:customer_name)
    c_id = customer.id
    add_id = {:order => {:customer_id => c_id}}
    params[:order] = params[:order].merge(add_id[:order])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
	def display_customers(customers)
		the_string = "<table class='table table-striped table-bordered'><thead><tr><th>Customer Name</th><th>Phone</th><th>Contact</th></tr></thead><tbody>"
		customers.each do |customer|
			cn = customer.name
			p = customer.phone
			c = customer.contact
			the_string += "<tr><td>#{cn}</td><td>#{p}</td><td>#{c}</td><td>#{link_to 'Show', customer}</td><td>#{link_to 'Edit', edit_customer_path(customer)}</td><td>#{link_to 'Destroy', customer, confirm: 'Are you sure?', method: :delete}</td><td>#{link_to 'Place Order', new_customer_order_path(customer)}</td><td>#{link_to 'View Oders', customer_orders_path(customer)}</td></tr>"
		end
		the_string += "</tbody></table>"
		the_string.html_safe
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	def customer_name(order)
		order.customer.name unless order.customer.nil?
	end

	def display_orders(customer)
		if customer.orders.first.nil? != true
		the_string = "<table class='table table-striped table-bordered'><thead><tr><th>Customer Name</th><th>Order ID</th><th>Item Name</th><th>Quantity</th><th>Total Cost</th></tr></thead><tbody>"
		customer.orders.each do |order|
			cn = Customer.find(order.customer_id).name
			id1 = order.id
			item = Item.find(order.item_id).name
			q = order.quantity
			tc = order.total_cost
			the_string += "<tr><td>#{cn}</td><td>#{id1}</td><td>#{item}</td><td>#{q}</td><td>#{tc}</td></tr>"
		end
		the_string += "</tbody></table>"
		the_string.html_safe
	  else
	  	the_string = "<div class='span10'><p>no orders have been placed</p></div>"
	  	the_string.html_safe
	  end
	end
end

app/views/customers/_footer.html.erb
<div class="footer">
<%= link_to 'New Customer', new_customer_path %>
</div>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/_head.html.erb
<div class="header">
	<h1 class="well well-small">Listing Customers</h1>
</div>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<div class="container">
<%= render 'head' %>
<br>
<div class="span3">
</div>

<div class"span10">

  <%= display_customers(@customers) %>
</div>
<%= render 'footer' %>
</div>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @customer.phone %>
</p>

<p>
  <b>Contact:</b>
  <%= @customer.contact %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment5</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/_foot.html.erb
<div class="footer">
<%= link_to 'Back', customers_path %>
</div>

app/views/orders/_form.html.erb
<%= form_for([@order.customer, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  
  <div class="field">
    <%= f.label :total_cost %><br />
    <%= f.text_field :total_cost %>
  </div>
  
  <div class="field">
    <%= f.label :customer_name %><br />
    <%= f.text_field :customer_name, :value=>customer_name(@order) %>
  </div>
  
  <div class="field">  
  <%= f.label :item %><br />  
  <%= f.collection_select :item_id, Item.all, :id, :name %>  
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_header.html.erb
<div class="header">
	<h1 class="well well-small">Listing orders for <%= Customer.find(params[:customer_id]).name %></h1>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="container">
<%= render 'header' %>
<br>
<div class="span3">
</div>

<div class"span10">

  <%= display_orders(Customer.find(params[:customer_id])) %>
</div>
<%= render 'foot' %>
</div>

app/views/orders/new.html.erb
<h1 class="well well-small">New order for <%= Customer.find(params[:customer_id]).name %></h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quantity:</b>
  <%= @order.quantity %>
</p>



<p>
  <b>Total cost:</b>
  <%= @order.total_cost %>
</p>

<p>
  <b>Customer:</b>
  <%= @order.customer.name %>
</p>

<p>
  <b>Item:</b>
  <%= @order.item.name %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>